#!/usr/bin/env bash

ROOT_DIR=$(pwd)

source $ROOT_DIR/.circleci/utils.sh

require PRODUCTION_API_URL $PRODUCTION_API_URL
require PRODUCTION_LANGUAGE $PRODUCTION_LANGUAGE
require PRODUCTION_HOST $PRODUCTION_HOST
require PRODUCTION_CREDENTIALS $PRODUCTION_CREDENTIALS
require PRODUCTION_CLOUDINARY_PRESET $PRODUCTION_CLOUDINARY_PRESET
require PRODUCTION_CLOUDINARY_URL $PRODUCTION_CLOUDINARY_URL


if [ "$CIRCLE_BRANCH" == "master" ]; then
    export REACT_APP_API_URL=$PRODUCTION_API_URL
    export REACT_APP_LANGUAGE=$PRODUCTION_LANGUAGE
    export REACT_APP_PRODUCTION_HOST=$PRODUCTION_HOST
    export REACT_APP_PRODUCTION_CREDENTIALS=$PRODUCTION_CREDENTIALS
    export REACT_APP_CLOUDINARY_PRESET=$PRODUCTION_CLOUDINARY_PRESET
    export REACT_APP_CLOUDINARY_URL=$PRODUCTION_CLOUDINARY_URL
fi

generateEnvFile(){
cat <<EOF
REACT_APP_API_URL=$REACT_APP_API_URL
REACT_APP_LANGUAGE=$REACT_APP_LANGUAGE
REACT_APP_CLOUDINARY_PRESET=$REACT_APP_CLOUDINARY_PRESET
REACT_APP_CLOUDINARY_URL=$REACT_APP_CLOUDINARY_URL
CI=false
EOF
}

generateEnvFile > ${ROOT_DIR}/.env
