#!/usr/bin/env bash

ROOT_DIR=$(pwd)

source $ROOT_DIR/.circleci/utils.sh

require PRODUCTION_API_URL $PRODUCTION_API_URL
require PRODUCTION_LANGUAGE $PRODUCTION_LANGUAGE
require PRODUCTION_HOST $PRODUCTION_HOST
require PRODUCTION_CREDENTIALS $PRODUCTION_CREDENTIALS


if [ "$CIRCLE_BRANCH" == "master" ]; then
    export REACT_APP_API_URL=$PRODUCTION_API_URL
    export REACT_APP_LANGUAGE=$PRODUCTION_LANGUAGE
    export REACT_APP_PRODUCTION_HOST=$PRODUCTION_HOST
    export REACT_APP_PRODUCTION_CREDENTIALS=$PRODUCTION_CREDENTIALS
fi

generateEnvFile(){
cat <<EOF
REACT_APP_API_URL=$REACT_APP_API_URL
REACT_APP_LANGUAGE=$REACT_APP_LANGUAGE
CI=false
EOF
}

generateEnvFile > ${ROOT_DIR}/.env
